name: Code Coverage Report

on:
  schedule:
    - cron: '0 21 * * *'  # 02:30 AM IST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: |
          mkdir -p "Daily audits"
          DATE=$(date +%F)
          pnpm test -- --coverage --coverageReporters=json-summary
          jq -r '"## Code Coverage – '+DATE+'", "Lines: \(.total.lines.pct)%", "Statements: \(.total.statements.pct)%"' coverage/coverage-summary.json \
            > "Daily audits/code-coverage-$DATE.md"

      - name: Commit report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "Daily audits/code-coverage-$(date +%F).md"
          git commit -m "Code Coverage Report" || echo "No changes"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
