name: Daily Link Check
on:
  schedule:
    - cron: '0 22 * * *'  # 03:30 IST
  workflow_dispatch:
    
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link report
        run: |
          mkdir -p "Daily audits"
          DATE=$(date +%F)
          npx linkinator ./ --stats --json > link-report.json
          echo "## Link Report – $DATE" > "Daily audits/link-check-$DATE.md"
          jq -r '.summary | to_entries[] | "\(.key): \(.value)"' link-report.json >> "Daily audits/link-check-$DATE.md"
      - name: Commit report
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add "Daily audits/link-check-$(date +%F).md"
          git commit -m "Daily Link Check" || echo "No changes"
          git push
