name: Automated Security Audit

on:
  schedule:
    - cron: '30 21 * * *'  # 03:00 AM IST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run pnpm audit and update markdown report
        id: audit
        run: |
          mkdir -p "Daily audits"
          DATE=$(date +%F)
          pnpm audit --json > audit.json || true
          echo -e "\n## Security Audit – $DATE" >> "Daily audits/security-audit.md"
          echo "| Severity | Count |" >> "Daily audits/security-audit.md"
          echo "|----------|-------|" >> "Daily audits/security-audit.md"
          jq -r '.metadata.vulnerabilities | to_entries | map("| \(.key) | \(.value) |") | .[]' audit.json >> "Daily audits/security-audit.md"
          echo -e "\n### Details" >> "Daily audits/security-audit.md"
          jq -r '.advisories | to_entries | map("**Advisory \(.key)**: \(.value.title)\n  - Package: \(.value.module_name)\n  - Severity: \(.value.severity)\n  - Advisory ID: \(.key)\n  - Advisory URL: https://www.npmjs.com/advisories/\(.key)\n  - Recommendation: \(.value.recommendation)\n") | .[]' audit.json >> "Daily audits/security-audit.md"
          CRITICAL=$(jq -r '.metadata.vulnerabilities.critical' audit.json)
          HIGH=$(jq -r '.metadata.vulnerabilities.high' audit.json)
          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
          echo "high=$HIGH" >> $GITHUB_OUTPUT

      - name: Check for Critical or High Vulnerabilities
        run: |
          CRITICAL=$(jq -r '.metadata.vulnerabilities.critical' audit.json)
          HIGH=$(jq -r '.metadata.vulnerabilities.high' audit.json)
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "Warning: Found $CRITICAL critical and $HIGH high vulnerabilities!" >&2
          else
            echo "No critical or high vulnerabilities found."
          fi

      - name: Commit and Push Report
        run: |
          git config user.name "rajtilak-2020"
          git config user.email "rajtilak1062020@gmail.com"
          git add "Daily audits/security-audit.md"
          git commit -m "Automated Security Audit - $(date +%F)"
          git push

      - name: Upload Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-${{ env.DATE }}
          path: |
            audit.json
            Daily audits/security-audit.md
